spring:
  application:
    name: recommendation-service
  profiles:
    group:
      docker: docker
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db

spring.mongodb.embedded.version: 5.0.5

server:
  port: 7002
  error:
    include-message: always

eureka:
  client:
    enabled: false

logging:
  level:
    root: info
    com.safecornerscoffee.microservices: debug

---
spring.config.activate.on-profile: docker

spring.data.mongodb.host: mongodb

server:
  port: 8080