spring:
  application:
    name: recommendation-service
  profiles:
    group:
      docker: docker

server:
  port: 7002
  error:
    include-message: always

eureka:
  client:
    enabled: false

logging:
  level:
    root: info
    com.safecornerscoffee.microservices: debug

---
spring.config.activate.on-profile: docker

server:
  port: 8080