language: java
dist: focal
jdk:
  - openjdk17
cache:
  directories:
    - '$HOME/.m2/repository'

services:
  - docker

addons:
  sonarcloud:
    organization: "safecornerscoffee"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=safecornerscoffee_microservices-on-kubernetes