spring:
  application:
    name: product-service
  profiles:
    group:
      docker: docker

  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
      auto-index-creation: true

spring.mongodb.embedded.version: 5.0.2

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

server:
  port: 7001
  error:
    include-message: always

eureka:
  client:
    enabled: false

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info
    org.springframework.data: debug
    com.safecornerscoffee: debug

---
spring.config.activate.on-profile: docker

server:
  port: 8080

spring.data.mongodb.host: mongodb

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka