spring:
  application:
    name: product-service
  profiles:
    group:
      docker: docker

  data:
    mongodb:
      auto-index-creation: true
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: product-db

spring.mongodb.embedded.version: 5.0.2

server:
  port: 7001
  error:
    include-message: always

eureka:
  client:
    enabled: false

logging:
  level:
    root: info
    org.springframework.data: debug
    com.safecornerscoffee: debug

---
spring.config.activate.on-profile: docker

spring.data.mongodb.host: mongodb

server:
  port: 8080