spring:
  application:
    name: product-service
  profiles:
    group:
      docker: docker

  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
      auto-index-creation: true

spring.mongodb.embedded.version: 5.0.2

spring.cloud.stream:
  defaultBinder: rabbit
  bindings:
    input:
      destination: products
      group: productsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

server:
  port: 7001
  error:
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info
    org.springframework.cloud.stream: debug
    com.safecornerscoffee: debug

---
spring.config.activate.on-profile: docker


spring.data.mongodb.host: mongodb

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka