spring:
  application:
    name: product-composite-service
  profiles:
    group:
      default: ["default", "swagger"]
      docker: ["docker", "swagger"]
  cloud:
    stream:
      default-binder: rabbit
      default.contentType: application/json
      bindings:
        output-products:
          destination: products
        output-recommendations:
          destination: recommendations
        output-reviews:
          destination: reviews
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 7000
  error:
    include-message: always

app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003

eureka:
  client:
    enabled: false

logging:
  level:
    root: info
    com.safecornerscoffee: debug