spring:
  application:
    name: product-composite-service
  profiles:
    group:
      default: ["default", "swagger"]
      docker: ["docker", "swagger"]
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        output-products:
          destination: products
        output-recommendations:
          destination: recommendations
        output-reviews:
          destination: reviews

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 7000
  error:
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info
    org.springframework.cloud.stream: debug
    com.safecornerscoffee.microservices: debug