spring:
  application:
    name: review-service
  profiles:
    group:
      docker: docker

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/review-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: create

  cloud:
    stream:
      default-binder: rabbit
      default.contentType: application/json
      bindings:
        input:
          destination: reviews
          group: reviewsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              republish-to-dlq: true
      kafka:
        binder:
          brokers: 127.0.0.1
          port: 5672
          username: guest
          password: guest
        bindings:
          input:
            consumer:
              enable-dlq: true


server:
  port: 7003
  error:
    include-message: always

eureka:
  client:
    enabled: false

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.hibernate.SQL : debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.safecornerscoffee.microservices: debug

---
spring.config.activate.on-profile: docker

server:
  port: 8080

spring.datasource.url: jdbc:mariadb://mariadb:3306/review-db

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka