spring:
  application:
    name: review-service
  profiles:
    group:
      docker: docker

server:
  port: 7003
  error:
    include-message: always

eureka:
  client:
    enabled: false

logging:
  level:
    root: INFO
    com.safecornerscoffee.microservices: debug

---
spring.config.activate.on-profile: docker

server:
  port: 8080